name: my_weather_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  http: ^1.2.1
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo_foreground.png"
  min_sdk_android: 21
  remove_alpha_ios: true 


flutter:
  uses-material-design: true
  assets:
    - assets/
